[package]
name = "cosmosdb-access"
version = "0.1.0"
edition = "2021"

[dependencies]
azure_data_cosmos = { version = "0.21.0", features = ["enable_reqwest"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"